Repository puppetlabs/puppet-runtime, pull requests merged in 2024-05, with the labels that each got.

#844 Bolt windows ed25519 support
  configs/components/ruby-2.7.8.rb
  configs/projects/bolt-runtime.rb
Labels: bug, enhancement

#845 fix augeas pkg.url
  configs/components/augeas.rb
Labels: bug

#850 Set Mend branch to master
  .github/workflows/mend.yaml
Labels: maintenance

#851 (CAT-1643) Update childprocess pin
  configs/components/rubygem-childprocess.rb
Labels: enhancement
